[tool.poetry]
name = "portfoliowebsite"
version = "0.1.0"
description = ""
authors = ["≈Åukasz Kuk <lukasz0104201@wp.pl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.20.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
